name: Linters

on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/**/*
      - tests/**/*
      - '*.json'
      - yarn.lock
  pull_request:
    paths:
      - '!*.MD'

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2.0.0

      - name: Install deps
        run: yarn
      - name: Run linters
        run: |
          git reset --soft HEAD^
          node_modules/.bin/lint-staged