name: build
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
#    paths:
#      - src/**/*
#      - tests/**/*
#      - '*.json'
#      - yarn.lock
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    name: electron test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn install
    - run: sudo apt-get install xvfb
    - uses: paambaati/codeclimate-action@v2.6.0
      env:
       CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
       coverageCommand: xvfb-run --auto-servernum yarn test:unit
