name: Tests

on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/**/*
      - tests/**/*
      - '*.json'
      - yarn.lock
  pull_request:
    paths:
      - '!*.MD'

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-18.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: |
            yarn tsc
            yarn test:unit
            yarn test:e2e